export const MOCK_COMPANY_DATA = {
  name: "Optimism",
  logo: "/src.jpg",
  description:
    "Optimism is a decentralized layer 2 scaling solution for Ethereum, which reduces transaction costs and latency and provides a better user experience.",
};

export const MOCK_JOB_DATA = [
  {
    position: "Product Designer",
    compensation: "$75-100k",
    location: "Remote",
    commitment: "Full-time",
    manager: "/src.png",
    teammates: ["/src.png", "/src.png"],
    posted: "2 days ago",
  },
  {
    position: "Software Engineer",
    compensation: "$90-120k",
    location: "San Francisco, CA",
    commitment: "Full-time",
    manager: "/src.png",
    teammates: ["/src.png", "/src.png"],
    posted: "1 day ago",
  },
  {
    position: "Data Analyst",
    compensation: "$70-90k",
    location: "New York, NY",
    commitment: "Part-time",
    manager: "/src.png",
    teammates: ["/src.png", "/src.png"],
    posted: "3 days ago",
  },
  {
    position: "Marketing Manager",
    compensation: "$80-110k",
    location: "Chicago, IL",
    commitment: "Full-time",
    manager: "/src.png",
    teammates: ["/src.png", "/src.png"],
    posted: "4 days ago",
  },
  {
    position: "Frontend Developer",
    compensation: "$85-115k",
    location: "Seattle, WA",
    commitment: "Full-time",
    manager: "/src.png",
    teammates: ["/src.png", "/src.png"],
    posted: "5 days ago",
  },
  {
    position: "UX/UI Designer",
    compensation: "$70-95k",
    location: "Austin, TX",
    commitment: "Full-time",
    manager: "/src.png",
    teammates: ["/src.png", "/src.png"],
    posted: "6 days ago",
  },
  {
    position: "Project Manager",
    compensation: "$80-105k",
    location: "Los Angeles, CA",
    commitment: "Full-time",
    manager: "/src.png",
    teammates: ["/src.png", "/src.png"],
    posted: "1 week ago",
  },
  {
    position: "Backend Developer",
    compensation: "$90-120k",
    location: "Boston, MA",
    commitment: "Full-time",
    manager: "/src.png",
    teammates: ["/src.png", "/src.png"],
    posted: "1 week ago",
  },
  {
    position: "Data Scientist",
    compensation: "$100-130k",
    location: "Denver, CO",
    commitment: "Full-time",
    manager: "/src.png",
    teammates: ["/src.png", "/src.png"],
    posted: "2 weeks ago",
  },
];
