export interface UserCombinedProfile {
  privy_did: string | null;
  name: string | null;
  photo_source: string | null;
  preferred_profile: string | null;
  available: boolean | null;
  position: string | null;
  employment_type: string | null;
  bio: string | null;
  booking_description: string | null;
  smart_wallet_address: string | null;
  unlock_calendar_fee: string | null;
  calendly_link: string | null;
  email: string | null;
  github_username: string | null;
  farcaster_fid: number | null;
  farcaster_username: string | null;
  farcaster_name: string | null;
  farcaster_bio: string | null;
  farcaster_photo: string | null;
  farcaster_address: string | null;
  linkedin_name: string | null;
  telegram_user_id: string | null;
  telegram_username: string | null;
  telegram_photo: string | null;
  x_username: string | null;
  x_photo: string | null;
}
